version: '3'
services:
  python-batch:
    build:
      context: ./python
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./python/src/:/mnt
    env_file:
      - .env.python
  # golang-batch-dev:
  #   build:
  #     context: ./golang
  #     target: dev
  #     dockerfile: Dockerfile
  #   # image: golang:1.20
  #   tty: true
  #   volumes:
  #     - ./golang/src/:/app
  #   env_file:
      # - .env.golang
  # golang-batch:
  #   build:
  #     context: ./golang
  #     dockerfile: Dockerfile
  #   tty: true
  #   volumes:
  #     - ./golang/src/:/app
  #   env_file:
  #     - .env.golang
